export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const TRANSACTION_START = 'TRANSACTION_START';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL';
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE';

export const TRANSACTION_EDIT_SUCCESS = "TRANSACTION_EDIT_SUCCESS";
export const TRANSACTION_FETCH_SUCCESS = "TRANSACTION_FETCH_SUCCESS";
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";

export const CURRENT_BALANCE_START = "CURRENT_BALANCE_START";
export const CURRENT_BALANCE_SUCCESS = "CURRENT_BALANCE_SUCCESS";
export const CURRENT_BALANCE_FAIL = "CURRENT_BALANCE_FAIL";
export const CURRENT_BALANCE_UPDATE = "CURRENT_BALANCE_UPDATE";